name = "CoreOptimized"
author = "SniperXJohn"
version = "1.4.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1af8acfa4f15fd68e6c8a83e91289ed7c4dc0563818ed395a27b46e4cd558d5d"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"
