name = "CoreOptimized"
author = "SniperXJohn"
version = "1.4.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cca1a875f9aa4c930a7080ab78d4800ac552e14b7702b63056f77f70ee2a6afd"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"
