name = "CoreOptimized"
author = "SniperXJohn"
version = "1.0.6-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70f39dc8f2eb06adb331432448432a307b34e69ac3bbd0a5032b87981e71bb7a"

[versions]
fabric = "0.16.10"
minecraft = "1.21.3"
