name = "CoreOptimized"
author = "SniperXJohn"
version = "1.0.6-beta.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb936fe761fa80345ffb27515d2e665440ee9483535eed78aa3cd56cdeef2cd9"

[versions]
fabric = "0.16.10"
minecraft = "1.21.3"
