name = "CoreOptimized"
author = "SniperXJohn"
version = "1.0.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fcfef24d46d44a3073c44e8785fc7c59305c3675f47816b07d6708ae9d2be28"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
