name = "CoreOptimized"
author = "SniperXJohn"
version = "1.0.6-beta.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8b938a7048e080b334c81979ae863ededd91c57805b7e301ebadd53620c5a23"

[versions]
fabric = "0.16.10"
minecraft = "1.21.3"
