name = "CoreOptimized"
author = "SniperXJohn"
version = "1.0.5-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55a2c4aac05246aece833653663bef4bc243c42f75fdede89f6af90a3861b1da"

[versions]
fabric = "0.16.10"
minecraft = "1.21.3"
