name = "CoreOptimized"
author = "SniperXJohn"
version = "1.0.6-beta.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02bdd586119c1789d58370ea217d7dc8fe099d03fdb662f5e43db28535e22a37"

[versions]
fabric = "0.16.14"
minecraft = "1.21.3"
