name = "CoreOptimized"
author = "SniperXJohn"
version = "1.0.4-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccf0ab3f1073b3adda739a561e928fce1553b7d1da75e1e017ad7f9d22f9f404"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
