name = "CoreOptimized"
author = "SniperXJohn"
version = "1.0.6-beta.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f8af4c8d5a31bd44782ac459d464c511d32df9574464b27d1f912261a095366"

[versions]
fabric = "0.16.14"
minecraft = "1.21.3"
