name = "CoreOptimized"
author = "SniperXJohn"
version = "1.0.5-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb7e96b2786a9deb3d40c0185ef8f20c72d57012a0b1f9b049032e6a9eb8fa71"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
