name = "CoreOptimized"
author = "SniperXJohn"
version = "1.0.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f3d1f16af3fd8bd26b2148379529fb0360b1054f0079f8f25dea2da76cd8b80"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
