name = "CoreOptimized"
author = "SniperXJohn"
version = "1.3.0-alpha.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8e5eead3bdc3a290953ebe2ae0f75691343200ac96a262c8f3e96031ff6f084"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
