name = "CoreOptimized"
author = "SniperXJohn"
version = "1.3.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "836b6983a9e22f4cff33fe73b4ace168ee8650ec9af9f96256b9b7de70cc0669"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
