name = "CoreOptimized"
author = "SniperXJohn"
version = "1.3.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7925354f11c125635099c21d7e7c6a5b55c462bdfa208995126ac4d091a55805"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
