name = "CoreOptimized"
author = "SniperXJohn"
version = "1.3.0-alpha.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6c978df1d0de03ea05983b8c6d4e7680feb110e67a5f98658e2beaeb51791d9"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
