name = "CoreOptimized"
author = "SniperXJohn"
version = "1.1.10-beta.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3f32e5dfa98451a24b631d14784ea84f9af74f8a191d724449e62632cb73668"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
