name = "CoreOptimized"
author = "SniperXJohn"
version = "1.1.10-beta.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c8b9cb74d26ae20019bed47d9f9f523e611227a8214145f9711cd3fe07b061c"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
