name = "CoreOptimized"
author = "SniperXJohn"
version = "1.1.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ecf091470deb7dc78734d3dc75b4a27a6b78a0041d3cdb360d2af1d0e0f5ee4"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
