name = "CoreOptimized"
author = "SniperXJohn"
version = "1.1.5-beta.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59f2f085036658bff92695f91ae459097a1afc17926b5ffdf47fc78f8797b907"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
