name = "CoreOptimized"
author = "SniperXJohn"
version = "1.1.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d1c5e1f267217e4b360c2f60f4a697f200b6755f993def13b388697194a3c46"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
