name = "CoreOptimized"
author = "SniperXJohn"
version = "1.1.8-beta.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b44d37c83025207596cbf3df384181c2f414c082dd8d16170d1210e6a2973b8a"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
