name = "CoreOptimized"
author = "SniperXJohn"
version = "1.1.4-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05a80d85cccf4f20923e744d1aacf9d6af89173fc617c7f1f6549c0a21ad9d1e"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
