name = "CoreOptimized"
author = "SniperXJohn"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c79936f51b63500e46a21ad37de7650f3bdbb582cfabe6f09de51394e1c34ee3"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
