name = "CoreOptimized"
author = "SniperXJohn"
version = "1.1.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca4e3edc924f676e25c5c1ae9d2441a58647c07285b3de0eb81280011742b4d7"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
