name = "CoreOptimized"
author = "SniperXJohn"
version = "1.1.10-beta.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3fcea496bdc2a500db81b307c181a07b9b088a1b760b99f2d96628971ac60d8"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
