name = "CoreOptimized"
author = "SniperXJohn"
version = "1.1.10-beta.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ae145815daed78dafdb7a3d16f6b135e39661f2a0bf63d41246358d87641744"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
