name = "CoreOptimized"
author = "SniperXJohn"
version = "1.1.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1c003cad92e0dd63a84fff7d2f40e2facb8152e603d16867826a5261611b6b3"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
