name = "CoreOptimized"
author = "SniperXJohn"
version = "1.1.10-beta.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f40db815c6560ecf99a17d00ebdeb2983853c9e7a5962d90215d995154689244"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
