name = "CoreOptimized"
author = "SniperXJohn"
version = "0.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cfa9102d67c6161c33f8505b4c2ee0bb55291213b4c97221dc6a316932c3f93"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
include_config_dir = true
