name = "CoreOptimized"
author = "SniperXJohn"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c05942e417bc0b0530d4d99b9007d55d1a192af0293c9c12d051dcae51d4046c"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
include_config_dir = true
