name = "CoreOptimized"
author = "SniperXJohn"
version = "0.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76f816c6c0a80c30d11628aad11076d6f3882c732719c7508426a10516a90717"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
include_config_dir = true
