name = "CoreOptimized"
author = "SniperXJohn"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "581278c42ca79e99fcadb26739ea0c6c4218a7a22261bf3b03f92663b2adfef0"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
include_config_dir = true
