name = "CoreOptimized"
author = "SniperXJohn"
version = "1.2.0-alpha.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9588824e33021774cde345826a772fdac66ee2af4d7ec568c3324b05bdfddb9d"

[versions]
fabric = "0.16.12"
minecraft = "1.21.5"
