name = "CoreOptimized"
author = "SniperXJohn"
version = "1.2.0-alpha.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcae8fbc0da20090c0caba4fe7877f179b94e6f724e59e129d75324f3c379db4"

[versions]
fabric = "0.16.13"
minecraft = "1.21.5"
