name = "CoreOptimized"
author = "SniperXJohn"
version = "1.2.0-beta.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f151bdb28335e1ca076f3149ca882ad75d280b9ae42d195a90e27d1a29ca6597"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
