name = "CoreOptimized"
author = "SniperXJohn"
version = "1.2.0-beta.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b29726ca9bdededd5401531e38110c6f6f68955f87a2f3256697ae72ac744d4f"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
