name = "CoreOptimized"
author = "SniperXJohn"
version = "1.2.0-beta.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7553b24709d6edde1fbd1917ba49efaaba7b37ef81e0d83ece5d84c363118aa7"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
