name = "CoreOptimized"
author = "SniperXJohn"
version = "1.2.0-beta.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3e0dd956860c5db202482180e3405c51bad9dcc79955a08405a2350db3ebf9d"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
