name = "CoreOptimized"
author = "SniperXJohn"
version = "1.2.0-beta.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd52f3ca842fc01808099d290fd7b7c4da2c5ec5d1eb87f4af97d3ce1e1e294a"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
