name = "CoreOptimized"
author = "SniperXJohn"
version = "1.2.0-beta.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "124812b7f513ef32f481ec0de11c1ed5661bca542604cdee16f9806c303b2ee1"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
