name = "CoreOptimized"
author = "SniperXJohn"
version = "1.2.0-beta.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c94bca793fcd11cb85cb86606407d9134b6165d2488a87ecfd47aaa6feedf063"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
