name = "CoreOptimized"
author = "SniperXJohn"
version = "1.2.0-beta.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa30d5e08b063cc96a7d53c470b26ea2e9d1ce2baecb445d611c7fac200fc695"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
