name = "CoreOptimized"
author = "SniperXJohn"
version = "1.0.1-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98b52b21db3bf7d46761ae6afe3d80e635d83dee3887ddfdacd250e2a7bf8927"

[versions]
fabric = "0.16.9"
minecraft = "1.21.2"
